version: "3.7"

services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest # https://docs.linuxserver.io/images/docker-speedtest-tracker
    container_name: speedtest-tracker
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - APP_KEY=${APP_KEY}
      - APP_URL=0.0.0.0
      - DB_CONNECTION=sqlite
      - SPEEDTEST_SCHEDULE=${SPEEDTEST_SCHEDULE}
      - SPEEDTEST_SERVERS=${SPEEDTEST_SERVERS}
      - DISPLAY_TIMEZONE=${TZ}
      - PRUNE_RESULTS_OLDER_THAN=${PRUNE_RESULTS_OLDER_THAN}
    volumes:
      - ./data:/config
    ports:
      - 59330:80
